project:
  type: website
  output-dir: docs

website:
  title: "siavashhabibi.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: evolution.qmd
        text: Evolution

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
