project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!README.md"

website:
  title: "SIAVASHHABIBI.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Structural Engineering"
        menu:
          - href: structural-engineering/index.qmd
            text: "Overview"
          - href: structural-engineering/mohrs-circle.qmd
            text: "Mohr's Circle"
          - href: structural-engineering/section-properties.qmd
            text: "Section Properties"
          - href: structural-engineering/simply-supported-beam.qmd
            text: "Simply Supported Beam"
          - href: structural-engineering/reinforced-concrete-beam.qmd
            text: "RC Beam Flexure"
          - href: structural-engineering/glass-panel.qmd
            text: "Glass Panel Load"
          - href: structural-engineering/structural-wood-panels.qmd
            text: "Structural Wood Panels"
          - href: structural-engineering/soil-pressure-coefficients.qmd
            text: "Soil Pressure Coefficients"
      - text: "Computational Geometry"
        menu:
          - href: computational-geometry/index.qmd
            text: "Overview"
          - href: computational-geometry/kd-tree.qmd
            text: "KD Tree"
          - href: computational-geometry/convex-hull.qmd
            text: "Convex Hull"
          - href: computational-geometry/evolution.qmd
            text: "Evolution"
          - href: computational-geometry/interpolators.qmd
            text: "Interpolators"
          - href: computational-geometry/parametric-curves.qmd
            text: "Parametric Curves"
          - href: computational-geometry/radial-patterns.qmd
            text: "Radial Patterns"
          - href: computational-geometry/random-generatives.qmd
            text: "Random Generatives"
          - href: computational-geometry/some-circles.qmd
            text: "Some Circles"
      - text: "Creative Coding"
        menu:
          - href: creative-coding/index.qmd
            text: "Overview"
          - href: creative-coding/matrix-background.qmd
            text: "Matrix Background"
          - href: creative-coding/click-and-delete.qmd
            text: "Click and Delete"
          - href: creative-coding/paint-brush.qmd
            text: "Paint Brush"
          - href: creative-coding/snap-to-grid.qmd
            text: "Snap to Grid"
          - href: creative-coding/hatches.qmd
            text: "Hatches"
          - href: creative-coding/mouse-tracker.qmd
            text: "Mouse Tracker"
          - href: creative-coding/svg-components.qmd
            text: "SVG Components"
      - text: "Programming"
        menu:
          - href: programming/index.qmd
            text: "Overview"
          - href: programming/etabspy.qmd
            text: "ETABSPY"
          - href: programming/etabsagent.qmd
            text: "ETABSAGENT"
          - href: programming/safepy.qmd
            text: "SAFEPY"
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
