project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!README.md"

website:
  title: "siavashhabibi.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Computational Geometry"
        menu:
          - href: computational-geometry/evolution.qmd
            text: "Evolution"
      - text: "Structural Engineering"
        menu:
          - href: structural-engineering/mohrs-circle.qmd
            text: "Mohr's Circle"

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
