project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!README.md"

website:
  title: "SIAVASHHABIBI.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Structural Engineering Tools"
        menu:
          - href: structural-engineering/index.qmd
            text: "Overview"
          - href: structural-engineering/mohrs-circle.qmd
            text: "Mohr's Circle"
      - text: "Programming"
        menu:
          - href: programming/index.qmd
            text: "Overview"
          - href: programming/etabspy.qmd
            text: "ETABSPY"
          - href: programming/etabsagent.qmd
            text: "ETABSAGENT"
          - href: programming/safepy.qmd
            text: "SAFEPY"
      - text: "Computational Geometry"
        menu:
          - href: computational-geometry/index.qmd
            text: "Overview"
          - href: computational-geometry/evolution.qmd
            text: "Evolution"
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
